[MaterialButton] fix(button): respect intrinsic icon width when iconGravity is view{Start/End}
material-components/material-components-android pull request #1997
Opened 2021-01-18 19:49 UTC by bmc08gt

To ensure the button text remains centered in the container, the icon's intrinsicWidth
needs to be taken into consideration.

closes #1996

2021-01-18 19:50 UTC, bmc08gt commented
@googlebot I signed it!

2021-01-18 19:54 UTC, DearDhruv approved these changes

2021-04-02 21:48 UTC, SupremeFergs approved these changes

2021-04-13 07:26 UTC, maxfie1d approved these changes

2021-07-14 15:26 UTC, drchen requested changes
I think the original behavior is WAI, according to the Material design spec:
https://material.io/components/buttons#interactive-demo

TBH I don't think we can just change it since it's an existing behavior conforming to the spec and being used everywhere. 

If you really need this behavior, I'll suggest you just customizing  your MaterialButton to implement the behavior.

2021-07-14 15:26 UTC, drchen commented on lib/java/com/google/android/material/button/MaterialButton.java
> +      adjustTextFromIcon();
Put this inside resetIconDrawable()?

2021-07-14 15:26 UTC, drchen commented on lib/java/com/google/android/material/button/MaterialButton.java
> +        setIconPadding(icon.getIntrinsicWidth());
Why do we need different logic here? Isn't the purpose "consuming" the icon width with a negative padding?

2021-07-15 01:36 UTC, bmc08gt commented
Yep I've done just that for a project.

2021-07-15 01:39 UTC, closed without merging