[MaterialDatePicker] Add a optional 'Clear' button
material-components/material-components-android pull request #2371
Opened 2021-09-13 21:27 UTC by DvTonder

Adds an optional 'Clear' button that be used to remove the user selected date as described in #1332 

closes #1332

2021-09-13 21:31 UTC, DvTonder commented
<!--
/* Font Definitions */
@font-face
	{font-family:Wingdings;
	panose-1:5 0 0 0 0 0 0 0 0 0;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Segoe UI Emoji";
	panose-1:2 11 5 2 4 2 4 2 2 3;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
h4
	{mso-style-priority:9;
	mso-style-link:"Heading 4 Char";
	mso-margin-top-alt:auto;
	margin-right:0cm;
	mso-margin-bottom-alt:auto;
	margin-left:0cm;
	font-size:12.0pt;
	font-family:"Calibri",sans-serif;
	font-weight:bold;}
h5
	{mso-style-priority:9;
	mso-style-link:"Heading 5 Char";
	mso-margin-top-alt:auto;
	margin-right:0cm;
	mso-margin-bottom-alt:auto;
	margin-left:0cm;
	font-size:10.0pt;
	font-family:"Calibri",sans-serif;
	font-weight:bold;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
code
	{mso-style-priority:99;
	font-family:"Courier New";}
span.DefaultFontHxMailStyle
	{mso-style-name:"Default Font HxMail Style";
	font-family:"Calibri",sans-serif;
	color:windowtext;
	font-weight:normal;
	font-style:normal;
	text-decoration:none none;}
span.Heading4Char
	{mso-style-name:"Heading 4 Char";
	mso-style-priority:9;
	mso-style-link:"Heading 4";
	font-family:"Calibri",sans-serif;
	font-weight:bold;}
span.Heading5Char
	{mso-style-name:"Heading 5 Char";
	mso-style-priority:9;
	mso-style-link:"Heading 5";
	font-family:"Calibri",sans-serif;
	font-weight:bold;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
/* List Definitions */
@list l0
	{mso-list-id:1070810839;
	mso-list-template-ids:-1;}
@list l0:level1
	{mso-level-number-format:bullet;
	mso-level-text:\F0B7;
	mso-level-tab-stop:36.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Symbol;}
@list l0:level2
	{mso-level-number-format:bullet;
	mso-level-text:o;
	mso-level-tab-stop:72.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:"Courier New";
	mso-bidi-font-family:"Times New Roman";}
@list l0:level3
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:108.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l0:level4
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:144.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l0:level5
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:180.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l0:level6
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:216.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l0:level7
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:252.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l0:level8
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:288.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l0:level9
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:324.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l1
	{mso-list-id:1778140507;
	mso-list-template-ids:-1;}
@list l1:level1
	{mso-level-number-format:bullet;
	mso-level-text:\F0B7;
	mso-level-tab-stop:36.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Symbol;}
@list l1:level2
	{mso-level-number-format:bullet;
	mso-level-text:o;
	mso-level-tab-stop:72.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:"Courier New";
	mso-bidi-font-family:"Times New Roman";}
@list l1:level3
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:108.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l1:level4
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:144.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l1:level5
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:180.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l1:level6
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:216.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l1:level7
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:252.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l1:level8
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:288.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
@list l1:level9
	{mso-level-number-format:bullet;
	mso-level-text:\F0A7;
	mso-level-tab-stop:324.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Wingdings;}
ol
	{margin-bottom:0cm;}
ul
	{margin-bottom:0cm;}
***@***.*** I signed it! From: google-cla[bot]Sent: September 13, 2021 5:28 PMTo: material-components/material-components-androidCc: DvTonder; AuthorSubject: Re: [material-components/material-components-android] [MaterialDatePicker] Add a optional 'Clear' button (#2371) Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).📝 Please visit https://cla.developers.google.com/ to sign.Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.What to do if you already signed the CLAIndividual signersIt's possible we don't have your GitHub username or you're using a different email address on your commit. Check your existing CLA data and verify that your email is set on your git commits.Corporate signersYour company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to go/cla#troubleshoot (Public version).The email used to register you as an authorized contributor must be the email used for the Git commit. Check your existing CLA data and verify that your email is set on your git commits.The email used to register you as an authorized contributor must also be attached to your GitHub account.ℹ️ Googlers: Go here for more info.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  

2021-09-17 23:04 UTC, DvTonder commented
@googlebot I signed it!

2021-10-01 15:26 UTC, drchen requested changes

2021-10-01 15:26 UTC, drchen commented on lib/java/com/google/android/material/datepicker/MaterialDatePicker.java
> +  private static final String CLEARABLE_KEY = "CLEARABLE_KEY";
Move to L70 with other "keys"

2021-10-01 15:26 UTC, drchen commented on lib/java/com/google/android/material/datepicker/MaterialDatePicker.java
> +      if (getDateSelector().isSelectionComplete()) {
clearButton.setEnabled(getDateSelector().isSelectionComplete());

2021-10-01 15:26 UTC, drchen commented on lib/java/com/google/android/material/datepicker/MaterialDatePicker.java
> +      clearButton.setTag(CLEAR_BUTTON_TAG);
Move it out of the if clause

2021-10-01 15:26 UTC, drchen commented on lib/java/com/google/android/material/datepicker/MaterialDatePicker.java
> +                  dismiss();
Seems not correct. Shouldn't we clear the selection here instead of dismiss the date picker?

2021-10-01 15:26 UTC, drchen commented on lib/java/com/google/android/material/datepicker/MaterialDatePicker.java
> +  /** The supplied listener is called when the user clicks the clear button. */
Move them to be together with other listener methods.

2021-10-01 15:26 UTC, drchen commented on lib/java/com/google/android/material/datepicker/MaterialDatePicker.java
> +   */
Add @return to explain the return value

2021-10-01 15:26 UTC, drchen commented on lib/java/com/google/android/material/datepicker/res/layout/mtrl_picker_actions.xml
> +    style="?attr/buttonBarNegativeButtonStyle"
Should be buttonBarNeutralButtonStyle?

2021-10-01 15:26 UTC, drchen commented on lib/java/com/google/android/material/datepicker/res/layout/mtrl_picker_actions.xml
> +  <Space
Replace containing LinearLayout with ConstraintLayout instead of using weighted space here.

2021-10-03 10:38 UTC, akkapon75 approved these changes

2021-10-03 10:43 UTC, akkapon75 approved these changes

2021-10-08 14:07 UTC, drchen commented
I didn't see the change. Did you forget to commit?

2021-10-09 16:38 UTC, DvTonder commented
> I didn't see the change. Did you forget to commit?

Have not committed yet.  Am toying with the implementation to experiment with different UXs

2021-10-11 15:36 UTC, DvTonder commented
Thank you!

2021-12-01 21:49 UTC, josefigueroa168 commented
Hi there, sorry for the delay. Do you mind resolving the new conflicts so I can review and confirm with @drchen and submit.

2021-12-01 22:08 UTC, DvTonder commented
@josefigueroa168 done as requested.  Thank you.

2022-01-29 18:42 UTC, DvTonder commented
Is there a possibility of this making it into 1.6?  

I'm really hoping to be able to remove all the copied DatePicker code from my app

2022-01-30 00:13 UTC, gubasza commented
> Adds an optional 'Clear' button that be used to remove the user selected date as described in #1332 
> 
> closes #1332 
>

2022-01-31 23:01 UTC, pekingme commented
@DvTonder, thanks again for the PR. Could you try to squash all your commits into one? I have some difficulties to pull your PR into internal repo. I think the merge master commits causes some change mapping issues.

2022-02-01 02:53 UTC, DvTonder commented
@pekingme I will see if I can figure it out.

2022-02-01 03:04 UTC, DvTonder commented
Single commit squashed change pull request sitting at #2542 

This obviates the need for this pull request

2022-02-01 17:19 UTC, DvTonder commented
@pekingme I'm not sure how to do what you are asking. I'm thinking easiest will be to copy the changed files to disk somewhere, delete my repo / fork altogether, then re-fork from the source and re-add the changed files I saved copies of as a new commit on the new fork and do a pull request.  Is that how to do it?

2022-02-01 19:52 UTC, pekingme commented
@DvTonder Thanks for trying. I'll do something similar on my end. Will delete the new PR you just created and associate the changes with this PR.

2022-02-01 20:11 UTC, DvTonder commented
@pekingme I'm standing by if you want me to try as well.  I can do so this evening.

2022-02-02 19:27 UTC, pekingme commented
@DvTonder I managed to pull it into the internal repo. During the internal review, we noticed that we need some feedback from design for full-screen use case. Stay tuned.

2022-05-06 08:38 UTC, DvTonder commented
It's been 3 months since the last update on this.  Any news?

2022-08-30 17:31 UTC, DvTonder commented
Good afternoon. This is my regular, 3 monthly, check-in on this topic.  

I see many commits in recent weeks for Date and Time picker. Dare I hope that this feature is also in the backlog?

2022-11-23 01:14 UTC, z4hyoung commented
Hey guys, 
When can I see this "CLEAR" button from official release?

2022-12-18 17:17 UTC, closed without merging