Update Color.md
material-components/material-components-android pull request #3158
Opened 2022-12-26 15:40 UTC by Arashvscode

Activate the Java magic color in the readme and give a more beautiful front!

2022-12-29 20:38 UTC, afohrman requested changes
Thanks for the PR! Looks good except for extra spacing, see comment within.

2022-12-29 20:38 UTC, afohrman commented on docs/theming/Color.md
> +``` java
Nit: extra space before "java".

Apply throughout.

2023-02-09 16:41 UTC, dsn5ft commented
Sorry to hear that, I'll manually apply these changes and close the PR then.

2023-02-09 18:27 UTC, closed without merging

2023-02-09 20:01 UTC, Arashvscode commented
> 

ok bro