[Slider] Fix ArithmeticException when calculating the phase
material-components/material-components-android pull request #4154
Opened 2024-04-25 16:46 UTC by pubiqq

2024-04-30 23:36 UTC, pekingme requested changes
Thanks for the PR!

2024-04-30 23:36 UTC, pekingme commented on lib/java/com/google/android/material/progressindicator/DrawableWithAnimatedVisibilityChange.java
> +    if (baseSpec.wavelength > 0 && baseSpec.speed != 0) {
Let's use `baseSpec.hasWavyEffect()` here.

2024-05-06 21:01 UTC, pubiqq commented
> Thanks for the PR!

You're welcome! 
Feel free to review [my other PRs](https://github.com/material-components/material-components-android/issues/3616) as well.

2024-05-06 21:04 UTC, pekingme approved these changes

2024-05-15 20:40 UTC, closed without merging